name: Run TikTok Downloader API

on:
  # 允许通过API调用（workflow_dispatch）
  workflow_dispatch:
    inputs:
      cookie:
        description: 'Cookie string (required)'
        required: true
        type: string
      action:
        description: 'Action type (detail, account, comment, search, live, etc.)'
        required: true
        type: string
      kwargs:
        description: 'Additional parameters in JSON format (optional)'
        required: false
        type: string
        default: '{}'

jobs:
  run-downloader:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.12'
        architecture: 'x64'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
      
    - name: Run TikTok Downloader API
      run: |
        python api_download.py "${{ github.event.inputs.cookie }}" "${{ github.event.inputs.action }}" "${{ github.event.inputs.kwargs }}"
      shell: bash
